import type {
  MaarifKazanimi,
  ClassRoom,
  Student,
  DefterKaydi,
  Announcement,
  SchoolCapacityStats,
  TeacherTavsiye,
} from "@/types/maarif";

export interface TeacherProfile {
  id: string;
  name: string;
  subject: string;
  avatarIcon: string;
  branchBadge: string;
  eImzaSertifika: string;
  defaultKonu: string;
  defaultKazanimKodu: string;
}

export const MOCK_TEACHERS: TeacherProfile[] = [
  {
    id: "tch-ing",
    name: "Canan Şahin",
    subject: "İngilizce",
    avatarIcon: "🇬🇧",
    branchBadge: "İngilizce Öğretmeni",
    eImzaSertifika: "MEB-AKİS E-İmza (Canan Şahin - İngilizce Öğrt.)",
    defaultKonu: "Friendship - Personal Qualities & Invitations",
    defaultKazanimKodu: "İNG.8.1.2",
  },
  {
    id: "tch-fen",
    name: "Sevgi Can",
    subject: "Fen Bilimleri",
    avatarIcon: "🔬",
    branchBadge: "Fen Bilimleri Öğretmeni",
    eImzaSertifika: "MEB-AKİS E-İmza (Sevgi Can - Fen Bilimleri Öğrt.)",
    defaultKonu: "Dünya'nın Dönme Ekseni Eğikliği ve Güneş Işınları",
    defaultKazanimKodu: "FEN.8.1.1",
  },
  {
    id: "tch-mat",
    name: "Ahmet Yılmaz",
    subject: "Matematik",
    avatarIcon: "📐",
    branchBadge: "Matematik Öğretmeni",
    eImzaSertifika: "MEB-AKİS E-İmza (Ahmet Yılmaz - Matematik Öğrt.)",
    defaultKonu: "Çarpanlar ve Katlar / EBOB ve EKOK",
    defaultKazanimKodu: "MAT.8.1.1",
  },
  {
    id: "tch-turkce",
    name: "Zeynep Kaya",
    subject: "Türkçe",
    avatarIcon: "📖",
    branchBadge: "Türkçe Öğretmeni",
    eImzaSertifika: "MEB-AKİS E-İmza (Zeynep Kaya - Türkçe Öğrt.)",
    defaultKonu: "Fiilimsiler (İsim-Fiil, Sıfat-Fiil, Zarf-Fiil)",
    defaultKazanimKodu: "TÜR.8.3.1",
  },
  {
    id: "tch-sosyal",
    name: "Kemal Arslan",
    subject: "T.C. İnkılap Tarihi ve Atatürkçülük",
    avatarIcon: "🇹🇷",
    branchBadge: "İnkılap Tarihi / Sosyal Öğretmeni",
    eImzaSertifika: "MEB-AKİS E-İmza (Kemal Arslan - Sosyal / İnkılap)",
    defaultKonu: "Mustafa Kemal'in Fikir Hayatını Etkileyen Olaylar ve Yazarlar",
    defaultKazanimKodu: "İNK.8.1.3",
  },
  {
    id: "tch-din",
    name: "Mustafa Koç",
    subject: "Din Kültürü ve Ahlak Bilgisi",
    avatarIcon: "🕌",
    branchBadge: "Din Kültürü Öğretmeni",
    eImzaSertifika: "MEB-AKİS E-İmza (Mustafa Koç - Din Kültürü Öğrt.)",
    defaultKonu: "İnsanın İradesi, Özgürlüğü ve Sorumluluğu (Tevekkül)",
    defaultKazanimKodu: "DİN.8.1.2",
  },
];

export const MOCK_MAARIF_KAZANIMLAR: MaarifKazanimi[] = [
  // ================= 8. SINIF KAZANIMLARI =================
  {
    id: "kazanim-mat-8-1",
    grade: 8,
    subject: "Matematik",
    kod: "MAT.8.1.1",
    title: "EBOB - EKOK Problemleri ve Modelleme",
    unite: "Çarpanlar ve Katlar",
    beceriAlani: "Kavramsal Beceri",
    erdemDeger: "Adalet",
    ogrenmeCiktisi: "İki doğal sayının en büyük ortak bölenini (EBOB) ve en küçük ortak katını (EKOK) hesaplar; ilgili problemleri çözer.",
    surecOdakliDegerlendirme: "Yeni nesil senaryolu problem çözme adımları ve modelleme rubriği.",
    isLgsKritik: true,
  },
  {
    id: "kazanim-mat-8-2",
    grade: 8,
    subject: "Matematik",
    kod: "MAT.8.1.2",
    title: "Aralarında Asal Sayılar ve Özellikleri",
    unite: "Çarpanlar ve Katlar",
    beceriAlani: "Kavramsal Beceri",
    erdemDeger: "Çalışkanlık",
    ogrenmeCiktisi: "Verilen iki doğal sayının aralarında asal olup olmadığını belirler.",
    surecOdakliDegerlendirme: "Asal çarpan algoritması inceleme formu.",
  },
  {
    id: "kazanim-tur-8-1",
    grade: 8,
    subject: "Türkçe",
    kod: "TÜR.8.3.1",
    title: "Fiilimsilerin Cümledeki İşlevleri ve Türleri",
    unite: "Dil Bilgisi: Fiilimsiler",
    beceriAlani: "Okuryazarlık",
    erdemDeger: "Çalışkanlık",
    ogrenmeCiktisi: "Fiilimsilerin cümledeki işlevlerini kavrar, türlerini (isim-fiil, sıfat-fiil, zarf-fiil) ayırt eder.",
    surecOdakliDegerlendirme: "Cümle içi ek analiz tablosu ve hata günlüğü.",
    isLgsKritik: true,
  },
  {
    id: "kazanim-fen-8-1",
    grade: 8,
    subject: "Fen Bilimleri",
    kod: "FEN.8.1.1",
    title: "Mevsimlerin Oluşumu ve Eksen Eğikliği",
    unite: "Mevsimler ve İklim",
    beceriAlani: "Okuryazarlık",
    erdemDeger: "Sorumluluk",
    ogrenmeCiktisi: "Mevsimlerin oluşumuna yönelik tahminlerde bulunur; Dünya'nın dönme ekseni eğikliğinin ve dolanma hareketinin etkisini modeller.",
    surecOdakliDegerlendirme: "Eksen eğikliği deney raporu ve akran değerlendirmesi.",
    isLgsKritik: true,
  },
  {
    id: "kazanim-fen-8-2",
    grade: 8,
    subject: "Fen Bilimleri",
    kod: "FEN.8.2.1",
    title: "DNA ve Genetik Kodun Yapısı",
    unite: "DNA ve Genetik Kod",
    beceriAlani: "Okuryazarlık",
    erdemDeger: "Merhamet",
    ogrenmeCiktisi: "Nükleotid, gen, DNA ve kromozom kavramlarını açıklayarak bu kavramlar arasında ilişki kurar.",
    surecOdakliDegerlendirme: "3 boyutlu origami DNA modeli ve sunum rubriği.",
  },
  {
    id: "kazanim-ink-8-1",
    grade: 8,
    subject: "T.C. İnkılap Tarihi ve Atatürkçülük",
    kod: "İNK.8.1.3",
    title: "Mustafa Kemal'in Fikir Hayatını Etkileyen Olaylar ve Yazarlar",
    unite: "Bir Kahraman Doğuyor",
    beceriAlani: "Kavramsal Beceri",
    erdemDeger: "Vatanseverlik",
    ogrenmeCiktisi: "Mustafa Kemal'in çocukluk ve öğrenim hayatından hareketle kişilik özelliklerinin oluşumunu analiz eder.",
    surecOdakliDegerlendirme: "Tarihsel karakter analiz tablosu ve kronoloji haritası.",
    isLgsKritik: true,
  },
  {
    id: "kazanim-ing-8-1",
    grade: 8,
    subject: "İngilizce",
    kod: "İNG.8.1.2",
    title: "Personal Qualities, Invitations & Making Excuses",
    unite: "Unit 1: Friendship",
    beceriAlani: "Sosyo-Duygusal",
    erdemDeger: "Dürüstlük",
    ogrenmeCiktisi: "Students will be able to accept and refuse invitations giving reasons and describe friendship qualities.",
    surecOdakliDegerlendirme: "İngilizce diyalog ve davet-mazeret mektubu rubriği.",
  },
  {
    id: "kazanim-din-8-1",
    grade: 8,
    subject: "Din Kültürü ve Ahlak Bilgisi",
    kod: "DİN.8.1.2",
    title: "İnsanın İradesi, Özgürlüğü ve Sorumluluğu (Tevekkül)",
    unite: "Kader İnancı",
    beceriAlani: "Kavramsal Beceri",
    erdemDeger: "Sorumluluk",
    ogrenmeCiktisi: "İnsanın ilmi, iradesi, sorumluluğu ile kader arasında ilişki kurar; tevekkül kavramını doğru kavrar.",
    surecOdakliDegerlendirme: "Ahlaki karar analizi ve tevekkül kompozisyon değerlendirmesi.",
  },
  {
    id: "kazanim-din-8-2",
    grade: 8,
    subject: "Din Kültürü ve Ahlak Bilgisi",
    kod: "DİN.8.1.1",
    title: "Kader ve Kaza İnancı: Evrendeki Fiziksel, Biyolojik ve Toplumsal Yasalar",
    unite: "Kader İnancı",
    beceriAlani: "Kavramsal Beceri",
    erdemDeger: "Adalet",
    ogrenmeCiktisi: "Kader ve kaza kavramlarını ayet ve hadislerle tanımlar; evrenin yasalarını irdeler.",
    surecOdakliDegerlendirme: "Kavram eşleştirme tablosu.",
  },

  // ================= 5. SINIF KAZANIMLARI =================
  {
    id: "kazanim-tur-5-1",
    grade: 5,
    subject: "Türkçe",
    kod: "TÜR.5.1.4",
    title: "Metindeki Deyim ve Atasözlerinin Anlama Katkısı",
    unite: "Söz Varlığı ve Deyimler",
    beceriAlani: "Okuryazarlık",
    erdemDeger: "Dürüstlük",
    ogrenmeCiktisi: "Metindeki deyim ve atasözlerinin anlama olan katkısını açıklar.",
    surecOdakliDegerlendirme: "Deyim kullanım gözlem formu ve hikaye yazımı.",
  },
  {
    id: "kazanim-mat-5-1",
    grade: 5,
    subject: "Matematik",
    kod: "MAT.5.1.1",
    title: "Milyonlu Doğal Sayıların Okunması ve Basamak Değerleri",
    unite: "Doğal Sayılar",
    beceriAlani: "Kavramsal Beceri",
    erdemDeger: "Adalet",
    ogrenmeCiktisi: "En çok dokuz basamaklı doğal sayıları okur, yazar ve basamak değerlerini belirtir.",
    surecOdakliDegerlendirme: "Basamak tablosu modelleme kontrol listesi.",
  },
  {
    id: "kazanim-fen-5-1",
    grade: 5,
    subject: "Fen Bilimleri",
    kod: "FEN.5.1.2",
    title: "Ay'ın Dönme ve Dolanma Hareketleri ile Evreleri",
    unite: "Güneş, Dünya ve Ay",
    beceriAlani: "Okuryazarlık",
    erdemDeger: "Merhamet",
    ogrenmeCiktisi: "Ay'ın dönme ve dolanma hareketlerini açıklar; evrelerini modeller.",
    surecOdakliDegerlendirme: "Haftalık gözlem günlüğü ve 3 boyutlu model sunumu.",
  },
  {
    id: "kazanim-sos-5-1",
    grade: 5,
    subject: "Sosyal Bilgiler",
    kod: "SOS.5.1.3",
    title: "Birey ve Toplum: Roller, Haklar ve Sorumluluklar",
    unite: "Birey ve Toplum",
    beceriAlani: "Sosyo-Duygusal",
    erdemDeger: "Adalet",
    ogrenmeCiktisi: "İçinde bulunduğu gruplarda aldığı roller ile rollerin gerektirdiği hak ve sorumlulukları ilişkilendirir.",
    surecOdakliDegerlendirme: "Hak ve sorumluluk eşleştirme afişi.",
  },
  {
    id: "kazanim-ing-5-1",
    grade: 5,
    subject: "İngilizce",
    kod: "İNG.5.1.1",
    title: "School Subjects, Timetables & Expressing Likes",
    unite: "Unit 1: Hello!",
    beceriAlani: "Sosyo-Duygusal",
    erdemDeger: "Saygı",
    ogrenmeCiktisi: "Students will be able to talk about school subjects and express likes and dislikes.",
    surecOdakliDegerlendirme: "İngilizce diyalog canlandırma ve konuşma rubriği.",
  },
  {
    id: "kazanim-din-5-1",
    grade: 5,
    subject: "Din Kültürü ve Ahlak Bilgisi",
    kod: "DİN.5.1.2",
    title: "Allah İnancı: Rahman ve Rahim Olan Allah",
    unite: "Allah İnancı",
    beceriAlani: "Sosyo-Duygusal",
    erdemDeger: "Merhamet",
    ogrenmeCiktisi: "Allah'ın (c.c.) her şeyi yaratan, yaşatan ve esirgeyen olduğunu kavrar.",
    surecOdakliDegerlendirme: "İyilik davranışı günlüğü.",
  },

  // ================= 6. SINIF KAZANIMLARI =================
  {
    id: "kazanim-tur-6-1",
    grade: 6,
    subject: "Türkçe",
    kod: "TÜR.6.1.4",
    title: "Kökler (İsim ve Fiil Kökü), Yapım ve Çekim Ekleri",
    unite: "Sözcükte Yapı",
    beceriAlani: "Okuryazarlık",
    erdemDeger: "Çalışkanlık",
    ogrenmeCiktisi: "Kelimelerin kök ve eklerini ayırt eder; yapım eklerinin türetme gücünü kavrar.",
    surecOdakliDegerlendirme: "Ek-kök çözümleme tablosu ve tanılayıcı ağaç.",
  },
  {
    id: "kazanim-mat-6-1",
    grade: 6,
    subject: "Matematik",
    kod: "MAT.6.1.1",
    title: "Üslü İfadeler ve İşlem Önceliği",
    unite: "Doğal Sayılarla İşlemler",
    beceriAlani: "Kavramsal Beceri",
    erdemDeger: "Çalışkanlık",
    ogrenmeCiktisi: "Bir doğal sayının kendisiyle tekrarlı çarpımını üslü ifade olarak yazar; işlem önceliğini uygular.",
    surecOdakliDegerlendirme: "İşlem önceliği basamak kontrol listesi.",
  },
  {
    id: "kazanim-fen-6-1",
    grade: 6,
    subject: "Fen Bilimleri",
    kod: "FEN.6.1.1",
    title: "Güneş Sistemi ve Gezegenlerin Özellikleri",
    unite: "Güneş Sistemi",
    beceriAlani: "Okuryazarlık",
    erdemDeger: "Saygı",
    ogrenmeCiktisi: "Güneş sistemindeki gezegenleri Güneş'e olan yakınlıklarına ve özelliklerine göre sıralar.",
    surecOdakliDegerlendirme: "Gezegen karşılaştırma matrisi.",
  },
  {
    id: "kazanim-sos-6-1",
    grade: 6,
    subject: "Sosyal Bilgiler",
    kod: "SOS.6.1.2",
    title: "Toplumsal Yardımlaşma, Dayanışma ve Sadaka Taşı Geleneği",
    unite: "Biz ve Değerlerimiz",
    beceriAlani: "Sosyo-Duygusal",
    erdemDeger: "Dürüstlük",
    ogrenmeCiktisi: "Toplumsal yardımlaşma ve dayanışmanın toplum huzuruna katkısını değerlendirir.",
    surecOdakliDegerlendirme: "Vakıf kültürü araştırma raporu.",
  },
  {
    id: "kazanim-ing-6-1",
    grade: 6,
    subject: "İngilizce",
    kod: "İNG.6.1.2",
    title: "Describing Daily Routines & Simple Present Tense",
    unite: "Unit 1: Life",
    beceriAlani: "Okuryazarlık",
    erdemDeger: "Sorumluluk",
    ogrenmeCiktisi: "Students will be able to talk about repeated actions and daily routines.",
    surecOdakliDegerlendirme: "Günlük rutin sunumu ve zaman çizelgesi.",
  },
  {
    id: "kazanim-din-6-1",
    grade: 6,
    subject: "Din Kültürü ve Ahlak Bilgisi",
    kod: "DİN.6.1.2",
    title: "Peygamberlerin Nitelikleri (Sıdk, Emanet, İsmet, Fetanet, Tebliğ)",
    unite: "Peygamber ve İlahi Kitap İnancı",
    beceriAlani: "Kavramsal Beceri",
    erdemDeger: "Dürüstlük",
    ogrenmeCiktisi: "Peygamberlerin sıfatlarını açıklar ve insanlık için önemini yorumlar.",
    surecOdakliDegerlendirme: "Kavram haritası ve ahlaki muhakeme formu.",
  },

  // ================= 7. SINIF KAZANIMLARI =================
  {
    id: "kazanim-tur-7-1",
    grade: 7,
    subject: "Türkçe",
    kod: "TÜR.7.3.1",
    title: "İş, Oluş ve Durum Fiilleri ile Haber/Dilek Kipleri",
    unite: "Fiillerde Anlam",
    beceriAlani: "Okuryazarlık",
    erdemDeger: "Çalışkanlık",
    ogrenmeCiktisi: "Fiillerin anlam özelliklerini ayırt eder ve kiplerle çekimler.",
    surecOdakliDegerlendirme: "Fiil sınıflandırma tablosu.",
  },
  {
    id: "kazanim-mat-7-1",
    grade: 7,
    subject: "Matematik",
    kod: "MAT.7.1.1",
    title: "Tam Sayılarla Çarpma ve Bölme İşlemleri",
    unite: "Tam Sayılarla İşlemler",
    beceriAlani: "Kavramsal Beceri",
    erdemDeger: "Adalet",
    ogrenmeCiktisi: "Tam sayılarla çarpma ve bölme işlemlerini yapar; ilgili problemleri modeller.",
    surecOdakliDegerlendirme: "Sayı pulları modelleme kontrol listesi.",
  },
  {
    id: "kazanim-fen-7-1",
    grade: 7,
    subject: "Fen Bilimleri",
    kod: "FEN.7.1.1",
    title: "Uzay Araştırmaları, Yapay Uydular ve Türkiye'nin Uzay Misyonu",
    unite: "Güneş Sistemi ve Ötesi",
    beceriAlani: "Okuryazarlık",
    erdemDeger: "Vatanseverlik",
    ogrenmeCiktisi: "Uzay araştırmalarında kullanılan teknolojileri ve Türkiye'nin yerli uydularını açıklar.",
    surecOdakliDegerlendirme: "Milli uydu araştırma kartı ve sunum.",
  },
  {
    id: "kazanim-sos-7-1",
    grade: 7,
    subject: "Sosyal Bilgiler",
    kod: "SOS.7.1.1",
    title: "Sen Dili - Ben Dili, Empati ve Etkili Dinleme",
    unite: "İletişim ve İnsan İlişkileri",
    beceriAlani: "Sosyo-Duygusal",
    erdemDeger: "Saygı",
    ogrenmeCiktisi: "İletişimi olumlu ve olumsuz etkileyen tutumları fark ederek kendi iletişim dilini geliştirir.",
    surecOdakliDegerlendirme: "Empati günlüğü ve rol canlandırma formu.",
  },
  {
    id: "kazanim-ing-7-1",
    grade: 7,
    subject: "İngilizce",
    kod: "İNG.7.1.2",
    title: "Describing People & Comparative Adjectives",
    unite: "Unit 1: Appearance and Personality",
    beceriAlani: "Sosyo-Duygusal",
    erdemDeger: "Saygı",
    ogrenmeCiktisi: "Students will be able to describe characters and physical appearances using comparatives.",
    surecOdakliDegerlendirme: "Kişilik profili poster çalışması.",
  },
  {
    id: "kazanim-din-7-1",
    grade: 7,
    subject: "Din Kültürü ve Ahlak Bilgisi",
    kod: "DİN.7.1.2",
    title: "Görünmeyen Âleme İman ve Meleklerin Görevleri",
    unite: "Melek ve Ahiret İnancı",
    beceriAlani: "Kavramsal Beceri",
    erdemDeger: "Sorumluluk",
    ogrenmeCiktisi: "Meleklerin özelliklerini ve görevlerini ayet ve hadisler ışığında açıklar.",
    surecOdakliDegerlendirme: "Meleklerin vazifeleri şeması.",
  },
];

export const MOCK_CLASSES: ClassRoom[] = [
  { id: "cls-8a", name: "8-A (LGS)", grade: 8, branch: "A", studentCount: 32, rehberOgretmen: "Ahmet Yılmaz (Matematik)" },
  { id: "cls-8b", name: "8-B (LGS)", grade: 8, branch: "B", studentCount: 30, rehberOgretmen: "Sevgi Can (Fen Bilimleri)" },
  { id: "cls-7a", name: "7-A", grade: 7, branch: "A", studentCount: 28, rehberOgretmen: "Zeynep Kaya (Türkçe)" },
  { id: "cls-6a", name: "6-A", grade: 6, branch: "A", studentCount: 26, rehberOgretmen: "Canan Şahin (İngilizce)" },
  { id: "cls-5a", name: "5-A", grade: 5, branch: "A", studentCount: 24, rehberOgretmen: "Kemal Arslan (Sosyal Bilgiler)" },
  { id: "cls-9a", name: "9-A", grade: 9, branch: "A", studentCount: 34, rehberOgretmen: "Mehmet Demir (Fizik)" },
];

export const MOCK_STUDENTS_ALL: Student[] = [
  // 8-A Öğrencileri
  { id: "std-1", studentNo: "801", name: "Ali Kerem Öztürk", classId: "cls-8a", className: "8-A", parentName: "Hakan Öztürk", parentPhone: "0532 555 1020", devamsizlikGun: 0.5, kazanimTamamlamaOrani: 94, entegreVeliKodu: "VELI-8A-801" },
  { id: "std-2", studentNo: "802", name: "Ayşe Nazlı Yıldırım", classId: "cls-8a", className: "8-A", parentName: "Sema Yıldırım", parentPhone: "0542 444 3040", devamsizlikGun: 0, kazanimTamamlamaOrani: 98, entegreVeliKodu: "VELI-8A-802" },
  { id: "std-3", studentNo: "803", name: "Barış Can Akın", classId: "cls-8a", className: "8-A", parentName: "Mustafa Akın", parentPhone: "0555 333 5060", devamsizlikGun: 1.5, kazanimTamamlamaOrani: 88, entegreVeliKodu: "VELI-8A-803" },
  { id: "std-4", studentNo: "804", name: "Elif Beyza Doğan", classId: "cls-8a", className: "8-A", parentName: "Nurgül Doğan", parentPhone: "0505 222 7080", devamsizlikGun: 0, kazanimTamamlamaOrani: 96, entegreVeliKodu: "VELI-8A-804" },
  { id: "std-5", studentNo: "805", name: "Emre Taha Şimşek", classId: "cls-8a", className: "8-A", parentName: "Cengiz Şimşek", parentPhone: "0533 111 9010", devamsizlikGun: 2, kazanimTamamlamaOrani: 82, entegreVeliKodu: "VELI-8A-805" },
  { id: "std-6", studentNo: "806", name: "Fatma Zehra Koç", classId: "cls-8a", className: "8-A", parentName: "Salih Koç", parentPhone: "0544 888 2030", devamsizlikGun: 0.5, kazanimTamamlamaOrani: 92, entegreVeliKodu: "VELI-8A-806" },
  { id: "std-7", studentNo: "807", name: "Kaan Mert Güneş", classId: "cls-8a", className: "8-A", parentName: "Derya Güneş", parentPhone: "0535 777 4050", devamsizlikGun: 1, kazanimTamamlamaOrani: 90, entegreVeliKodu: "VELI-8A-807" },
  { id: "std-8", studentNo: "808", name: "Zeynep İrem Çetin", classId: "cls-8a", className: "8-A", parentName: "Murat Çetin", parentPhone: "0530 666 6070", devamsizlikGun: 0, kazanimTamamlamaOrani: 97, entegreVeliKodu: "VELI-8A-808" },
  // 7-A Öğrencileri
  { id: "std-701", studentNo: "701", name: "Zeynep Doğan", classId: "cls-7a", className: "7-A", parentName: "Selin Doğan", parentPhone: "0536 123 4567", devamsizlikGun: 0, kazanimTamamlamaOrani: 95, entegreVeliKodu: "VELI-7A-701" },
  { id: "std-702", studentNo: "702", name: "Kerem Taş", classId: "cls-7a", className: "7-A", parentName: "Fatih Taş", parentPhone: "0537 234 5678", devamsizlikGun: 1, kazanimTamamlamaOrani: 89, entegreVeliKodu: "VELI-7A-702" },
  // 6-A Öğrencileri
  { id: "std-601", studentNo: "601", name: "Deniz Kaya", classId: "cls-6a", className: "6-A", parentName: "Mehmet Kaya", parentPhone: "0538 345 6789", devamsizlikGun: 0, kazanimTamamlamaOrani: 93, entegreVeliKodu: "VELI-6A-601" },
  { id: "std-602", studentNo: "602", name: "Sude Aydın", classId: "cls-6a", className: "6-A", parentName: "Berrin Aydın", parentPhone: "0539 456 7890", devamsizlikGun: 0.5, kazanimTamamlamaOrani: 91, entegreVeliKodu: "VELI-6A-602" },
  // 5-A Öğrencileri
  { id: "std-501", studentNo: "501", name: "Efe Yılmaz", classId: "cls-5a", className: "5-A", parentName: "Ayşe Yılmaz", parentPhone: "0540 567 8901", devamsizlikGun: 0, kazanimTamamlamaOrani: 96, entegreVeliKodu: "VELI-5A-501" },
  { id: "std-502", studentNo: "502", name: "Yağmur Çelik", classId: "cls-5a", className: "5-A", parentName: "Gökhan Çelik", parentPhone: "0541 678 9012", devamsizlikGun: 0, kazanimTamamlamaOrani: 94, entegreVeliKodu: "VELI-5A-502" },
];

export const MOCK_STUDENTS_9A = MOCK_STUDENTS_ALL; // Geriye dönük uyumluluk

export const MOCK_DEFTER_KAYITLARI: DefterKaydi[] = [
  {
    id: "def-1",
    date: "2026-09-25",
    lessonHour: 1,
    classId: "cls-8a",
    className: "8-A",
    subject: "Matematik",
    teacherId: "tch-mat",
    teacherName: "Ahmet Yılmaz (Matematik)",
    topic: "Çarpanlar ve Katlar / EBOB ve EKOK Problemleri",
    selectedKazanimlar: [MOCK_MAARIF_KAZANIMLAR[0]],
    yoklama: [
      { studentId: "std-1", studentName: "Ali Kerem Öztürk", studentNo: "801", status: "geldi" },
      { studentId: "std-2", studentName: "Ayşe Nazlı Yıldırım", studentNo: "802", status: "geldi" },
      { studentId: "std-3", studentName: "Barış Can Akın", studentNo: "803", status: "gelmedi", aciklama: "Rapor bekleniyor" },
      { studentId: "std-4", studentName: "Elif Beyza Doğan", studentNo: "804", status: "geldi" },
      { studentId: "std-5", studentName: "Emre Taha Şimşek", studentNo: "805", status: "gec", aciklama: "10 dk geç katıldı" },
      { studentId: "std-6", studentName: "Fatma Zehra Koç", studentNo: "806", status: "geldi" },
      { studentId: "std-7", studentName: "Kaan Mert Güneş", studentNo: "807", status: "geldi" },
      { studentId: "std-8", studentName: "Zeynep İrem Çetin", studentNo: "808", status: "geldi" },
    ],
    tavsiye: "MEB 8. Sınıf LGS Örnek Sorular Kitapçığı EBOB-EKOK konusundan 25 yeni nesil problem çözülecek.",
    odev: "MEB 8. Sınıf LGS Örnek Sorular Kitapçığı EBOB-EKOK konusundan 25 yeni nesil problem çözülecek.",
    ogretmenNotu: "Sınıfın yeni nesil modelleme kavrayışı çok yüksek, soru analizleri başarılı.",
    imzalandi: true,
    onaylayanYonetici: "Müdür Yrd. Selim Aras (E-İmzalı)",
  },
  {
    id: "def-2",
    date: "2026-09-25",
    lessonHour: 2,
    classId: "cls-8a",
    className: "8-A",
    subject: "Türkçe",
    teacherId: "tch-turkce",
    teacherName: "Zeynep Kaya (Türkçe)",
    topic: "Fiilimsiler (İsim-Fiil, Sıfat-Fiil, Zarf-Fiil)",
    selectedKazanimlar: [MOCK_MAARIF_KAZANIMLAR[2]],
    yoklama: [
      { studentId: "std-1", studentName: "Ali Kerem Öztürk", studentNo: "801", status: "geldi" },
      { studentId: "std-2", studentName: "Ayşe Nazlı Yıldırım", studentNo: "802", status: "geldi" },
      { studentId: "std-3", studentName: "Barış Can Akın", studentNo: "803", status: "gelmedi" },
      { studentId: "std-4", studentName: "Elif Beyza Doğan", studentNo: "804", status: "geldi" },
      { studentId: "std-5", studentName: "Emre Taha Şimşek", studentNo: "805", status: "geldi" },
      { studentId: "std-6", studentName: "Fatma Zehra Koç", studentNo: "806", status: "geldi" },
      { studentId: "std-7", studentName: "Kaan Mert Güneş", studentNo: "807", status: "geldi" },
      { studentId: "std-8", studentName: "Zeynep İrem Çetin", studentNo: "808", status: "geldi" },
    ],
    tavsiye: "MEB 8. Sınıf LGS Türkçe Çalışma Fasikülü Sayfa 30-36 (Kazanım Testi 5) çözülecek.",
    odev: "MEB 8. Sınıf LGS Türkçe Çalışma Fasikülü Sayfa 30-36 (Kazanım Testi 5) çözülecek.",
    ogretmenNotu: "Kalıplaşmış isim ile fiilimsi ayrımı üzerine kavram yanılgısı vurgulandı.",
    imzalandi: true,
    onaylayanYonetici: "Müdür Yrd. Selim Aras (E-İmzalı)",
  },
  {
    id: "def-3",
    date: "2026-09-25",
    lessonHour: 3,
    classId: "cls-8a",
    className: "8-A",
    subject: "Fen Bilimleri",
    teacherId: "tch-fen",
    teacherName: "Sevgi Can (Fen Bilimleri)",
    topic: "Dünya'nın Dönme Ekseni Eğikliği ve Güneş Işınları",
    selectedKazanimlar: [MOCK_MAARIF_KAZANIMLAR[3]],
    yoklama: [
      { studentId: "std-1", studentName: "Ali Kerem Öztürk", studentNo: "801", status: "geldi" },
      { studentId: "std-2", studentName: "Ayşe Nazlı Yıldırım", studentNo: "802", status: "geldi" },
      { studentId: "std-3", studentName: "Barış Can Akın", studentNo: "803", status: "geldi" },
      { studentId: "std-4", studentName: "Elif Beyza Doğan", studentNo: "804", status: "geldi" },
      { studentId: "std-5", studentName: "Emre Taha Şimşek", studentNo: "805", status: "geldi" },
      { studentId: "std-6", studentName: "Fatma Zehra Koç", studentNo: "806", status: "geldi" },
      { studentId: "std-7", studentName: "Kaan Mert Güneş", studentNo: "807", status: "geldi" },
      { studentId: "std-8", studentName: "Zeynep İrem Çetin", studentNo: "808", status: "geldi" },
    ],
    tavsiye: "MEB 8. Sınıf Fen Bilimleri Beceri Temelli Sorular Sayfa 12-18 arası 25 soru çözülecek.",
    odev: "MEB 8. Sınıf Fen Bilimleri Beceri Temelli Sorular Sayfa 12-18 arası 25 soru çözülecek.",
    ogretmenNotu: "Işık açısı ve gölge boyu deney düzeneği başarılı şekilde incelendi.",
    imzalandi: true,
    onaylayanYonetici: "Müdür Yrd. Selim Aras (E-İmzalı)",
  },
  {
    id: "def-4",
    date: "2026-09-25",
    lessonHour: 4,
    classId: "cls-8a",
    className: "8-A",
    subject: "İngilizce",
    teacherId: "tch-ing",
    teacherName: "Canan Şahin (İngilizce)",
    topic: "Friendship - Personal Qualities & Invitations",
    selectedKazanimlar: [MOCK_MAARIF_KAZANIMLAR[6]],
    yoklama: [
      { studentId: "std-1", studentName: "Ali Kerem Öztürk", studentNo: "801", status: "geldi" },
      { studentId: "std-2", studentName: "Ayşe Nazlı Yıldırım", studentNo: "802", status: "geldi" },
      { studentId: "std-3", studentName: "Barış Can Akın", studentNo: "803", status: "geldi" },
      { studentId: "std-4", studentName: "Elif Beyza Doğan", studentNo: "804", status: "geldi" },
      { studentId: "std-5", studentName: "Emre Taha Şimşek", studentNo: "805", status: "geldi" },
      { studentId: "std-6", studentName: "Fatma Zehra Koç", studentNo: "806", status: "geldi" },
      { studentId: "std-7", studentName: "Kaan Mert Güneş", studentNo: "807", status: "geldi" },
      { studentId: "std-8", studentName: "Zeynep İrem Çetin", studentNo: "808", status: "geldi" },
    ],
    tavsiye: "MEB 8th Grade English LGS Master Test Page 18-24 çözülecek.",
    odev: "MEB 8th Grade English LGS Master Test Page 18-24 çözülecek.",
    ogretmenNotu: "Öğrencilerin davet ve mazeret cümle yapılarını kavrayışı oldukça akıcı.",
    imzalandi: true,
    onaylayanYonetici: "Müdür Yrd. Selim Aras (E-İmzalı)",
  },
  {
    id: "def-5",
    date: "2026-09-25",
    lessonHour: 5,
    classId: "cls-8a",
    className: "8-A",
    subject: "T.C. İnkılap Tarihi ve Atatürkçülük",
    teacherId: "tch-sosyal",
    teacherName: "Kemal Arslan (İnkılap Tarihi)",
    topic: "Mustafa Kemal'in Fikir Hayatını Etkileyen Olaylar ve Yazarlar",
    selectedKazanimlar: [MOCK_MAARIF_KAZANIMLAR[5]],
    yoklama: [
      { studentId: "std-1", studentName: "Ali Kerem Öztürk", studentNo: "801", status: "geldi" },
      { studentId: "std-2", studentName: "Ayşe Nazlı Yıldırım", studentNo: "802", status: "geldi" },
      { studentId: "std-3", studentName: "Barış Can Akın", studentNo: "803", status: "geldi" },
      { studentId: "std-4", studentName: "Elif Beyza Doğan", studentNo: "804", status: "geldi" },
      { studentId: "std-5", studentName: "Emre Taha Şimşek", studentNo: "805", status: "geldi" },
      { studentId: "std-6", studentName: "Fatma Zehra Koç", studentNo: "806", status: "geldi" },
      { studentId: "std-7", studentName: "Kaan Mert Güneş", studentNo: "807", status: "geldi" },
      { studentId: "std-8", studentName: "Zeynep İrem Çetin", studentNo: "808", status: "geldi" },
    ],
    tavsiye: "MEB 8. Sınıf İnkılap Tarihi LGS Testleri Sayfa 22-28 arası çözülecek.",
    odev: "MEB 8. Sınıf İnkılap Tarihi LGS Testleri Sayfa 22-28 arası çözülecek.",
    ogretmenNotu: "Mustafa Kemal'in düşünce yapısını şekillendiren şehirler ve yazarlar harita üzerinde eşleştirildi.",
    imzalandi: true,
    onaylayanYonetici: "Müdür Yrd. Selim Aras (E-İmzalı)",
  },
  {
    id: "def-6",
    date: "2026-09-25",
    lessonHour: 6,
    classId: "cls-8a",
    className: "8-A",
    subject: "Din Kültürü ve Ahlak Bilgisi",
    teacherId: "tch-din",
    teacherName: "Mustafa Koç (Din Kültürü)",
    topic: "İnsanın İradesi, Özgürlüğü ve Sorumluluğu (Tevekkül)",
    selectedKazanimlar: [MOCK_MAARIF_KAZANIMLAR[7]],
    yoklama: [
      { studentId: "std-1", studentName: "Ali Kerem Öztürk", studentNo: "801", status: "geldi" },
      { studentId: "std-2", studentName: "Ayşe Nazlı Yıldırım", studentNo: "802", status: "geldi" },
      { studentId: "std-3", studentName: "Barış Can Akın", studentNo: "803", status: "geldi" },
      { studentId: "std-4", studentName: "Elif Beyza Doğan", studentNo: "804", status: "geldi" },
      { studentId: "std-5", studentName: "Emre Taha Şimşek", studentNo: "805", status: "geldi" },
      { studentId: "std-6", studentName: "Fatma Zehra Koç", studentNo: "806", status: "geldi" },
      { studentId: "std-7", studentName: "Kaan Mert Güneş", studentNo: "807", status: "geldi" },
      { studentId: "std-8", studentName: "Zeynep İrem Çetin", studentNo: "808", status: "geldi" },
    ],
    tavsiye: "Tevekkül ve sorumluluk kavramları arasındaki farkı açıklayan 1 sayfalık kompozisyon yazılacak.",
    odev: "Tevekkül ve sorumluluk kavramları arasındaki farkı açıklayan 1 sayfalık kompozisyon yazılacak.",
    ogretmenNotu: "Cüzi irade ile külli irade arasındaki fark ve sorumluluk bilinci pekiştirildi.",
    imzalandi: true,
    onaylayanYonetici: "Müdür Yrd. Selim Aras (E-İmzalı)",
  },
];

export const MOCK_TEACHER_TAVSIYELER: TeacherTavsiye[] = [
  {
    id: "tav-1",
    studentId: "std-1",
    studentName: "Ali Kerem Öztürk",
    teacherId: "tch-mat",
    teacherName: "Ahmet Yılmaz (Matematik)",
    subject: "Matematik",
    tarih: "2026-09-25",
    haftalikKonu: "Çarpanlar ve Katlar / EBOB-EKOK",
    tavsiyeMetni: "Ali Kerem derste EBOB-EKOK problemlerinde bütünden parçaya akıl yürütmeyi çok hızlı kavradı. LGS Örnek Sorular Kitapçığı Sayfa 14-22 arasındaki yeni nesil soruları çözmesi modelleme gücünü pekiştirecektir.",
    beceriAlani: "Kavramsal Beceri (Akıl Yürütme)",
    oncelik: "onemli",
  },
  {
    id: "tav-2",
    studentId: "std-1",
    studentName: "Ali Kerem Öztürk",
    teacherId: "tch-turkce",
    teacherName: "Zeynep Kaya (Türkçe)",
    subject: "Türkçe",
    tarih: "2026-09-24",
    haftalikKonu: "Fiilimsiler ve Kalıcı İsim Ayrımı",
    tavsiyeMetni: "Fiilimsilerin türlerini bulmada ve kalıplaşmış isimleri ayırt etmede harika bir dikkat sergiledi. Tebrik eder, günlük paragraf soru çözümlerine devam etmesini tavsiye ederim.",
    beceriAlani: "Okuryazarlık (Dil Bilgisi)",
    oncelik: "tebrik",
  },
  {
    id: "tav-3",
    studentId: "std-1",
    studentName: "Ali Kerem Öztürk",
    teacherId: "tch-fen",
    teacherName: "Sevgi Can (Fen Bilimleri)",
    subject: "Fen Bilimleri",
    tarih: "2026-09-24",
    haftalikKonu: "Mevsimlerin Oluşumu ve Eksen Eğikliği",
    tavsiyeMetni: "Dünya'nın Güneş'e olan mesafesinin mevsimlerle ilgisi olmadığını, eksen eğikliğinin önemini deney modelinde başarıyla açıkladı.",
    beceriAlani: "Fen Okuryazarlığı",
    oncelik: "tebrik",
  },
  {
    id: "tav-4",
    studentId: "std-1",
    studentName: "Ali Kerem Öztürk",
    teacherId: "tch-ing",
    teacherName: "Canan Şahin (İngilizce)",
    subject: "İngilizce",
    tarih: "2026-09-23",
    haftalikKonu: "Friendship & Personal Traits",
    tavsiyeMetni: "İngilizce davet ve mazeret ifadelerini ('I'd love to, but...') diyalog canlandırmasında çok akıcı kullandı.",
    beceriAlani: "Sosyo-Duygusal İletişim",
    oncelik: "normal",
  },
  {
    id: "tav-5",
    studentId: "std-1",
    studentName: "Ali Kerem Öztürk",
    teacherId: "tch-sosyal",
    teacherName: "Kemal Arslan (İnkılap Tarihi)",
    subject: "T.C. İnkılap Tarihi ve Atatürkçülük",
    tarih: "2026-09-23",
    haftalikKonu: "Mustafa Kemal'in Fikir Hayatı",
    tavsiyeMetni: "Manastır ve Selanik şehirlerinin Mustafa Kemal üzerindeki etkilerini çok iyi tahlil etti.",
    beceriAlani: "Tarihsel Düşünme",
    oncelik: "normal",
  },
  {
    id: "tav-6",
    studentId: "std-1",
    studentName: "Ali Kerem Öztürk",
    teacherId: "tch-din",
    teacherName: "Mustafa Koç (Din Kültürü)",
    subject: "Din Kültürü ve Ahlak Bilgisi",
    tarih: "2026-09-22",
    haftalikKonu: "İnsanın İradesi ve Tevekkül",
    tavsiyeMetni: "Tevekkül ve sorumluluk erdemi üzerine hazırladığı analiz metni takdire şayandı.",
    beceriAlani: "Ahlaki Muhakeme",
    oncelik: "tebrik",
  },
];

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann-1",
    title: "Türkiye Yüzyılı Maarif Modeli 1. Dönem Veli Bilgilendirme Toplantısı",
    content: "Yeni müfredatın beceri temelli yapısı, süreç odaklı değerlendirme rubrikleri ve veli takip portalımızın kullanımı hakkında 28 Eylül Cumartesi saat 10:30'da okulumuz konferans salonunda toplantı yapılacaktır.",
    target: "veliler",
    author: "Okul Yönetimi",
    date: "2026-09-25",
    priority: "onemli",
  },
  {
    id: "ann-2",
    title: "Dijital Sınıf Defteri Günlük İmzalama Hatırlatması",
    content: "Değerli Öğretmenlerimiz; MEB mevzuatı gereği her ders saati bitiminde yoklama ve Maarif Modeli öğrenme çıktısı seçimlerinin dijital deftere işlenerek e-imzalanması gerekmektedir.",
    target: "ogretmenler",
    author: "Müdürlük",
    date: "2026-09-25",
    priority: "acil",
  },
  {
    id: "ann-3",
    title: "Matematik ve Fen Bilimleri LGS Süreç Değerlendirme Tavsiyeleri",
    content: "8. Sınıflar EBOB-EKOK ve Mevsimler teması LGS yeni nesil tavsiye görevleri sisteme yüklenmiştir.",
    target: "sinif",
    targetClassId: "cls-8a",
    author: "Ahmet Yılmaz (Matematik)",
    date: "2026-09-24",
    priority: "normal",
  },
];

export const MOCK_SCHOOL_STATS: SchoolCapacityStats = {
  totalTeachers: 154,
  totalClasses: 40,
  totalStudents: 1580,
  todayAttendanceRate: 97.8,
  defterFillRate: 98.4,
  weeklyCompletedKazanimCount: 420,
  activeConcurrentUsers: 1420,
};
